<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>This has been released under the beer-ware license, see the LICENSE file.</string>
	<key>fileTypes</key>
	<array>
		<string>fdl</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>keyEquivalent</key>
	<string>^~G</string>
	<key>name</key>
	<string>Gezel</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.untitled</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.untitled</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.fdl</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(//).*?($\n?|(?=\?&gt;))</string>
			<key>name</key>
			<string>comment.line.double-slash.fdl</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(dp|fsm|ipblock|hardwired)\s+(?:([a-zA-Z_][a-zA-Z0-9_]*))\s*(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.fdl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.fdl</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.fdl</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>meta.function.arguments.fdl</string>
			<key>end</key>
			<string>\)\s*{</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.end.fdl</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.with-arguments.fdl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.fdl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.state.fdl</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.fdl</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\s*(in|out|\s*)\s+(?:[a-zA-Z_][a-zA-Z0-9_]*)\s*(?=,|:|;)</string>
					<key>name</key>
					<string>meta.state.argument.fdl</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#types</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numbers</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(sfg|dp|system|always)\s+(?:([a-zA-Z_][a-zA-Z0-9_]*)|\{)(?:\s+(?:\:)\s+([a-zA-Z_][a-zA-Z0-9_]*)|)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.fdl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.fdl</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.fdl</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>meta.function.arguments.fdl</string>
			<key>end</key>
			<string></string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.end.fdl</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.no-arguments.fdl</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(initial|state)(\s)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.type.state.fdl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.begin.fdl</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>meta.state.arguments.fdl</string>
			<key>end</key>
			<string>;</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.end.fdl</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.state.fdl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.state.fdl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.fdl</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\s*([a-zA-Z_][a-zA-Z0-9_]*)\s*(?=,|;)</string>
					<key>name</key>
					<string>meta.state.argument.fdl</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>@[a-zA-Z_][a-zA-Z0-9_]*</string>
			<key>name</key>
			<string>constant.state.fdl</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.state.arrow.fdl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.state.fdl</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.end.fdl</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\-&gt;)\s*([a-zA-Z_][a-zA-Z0-9_]*)\s*;</string>
			<key>name</key>
			<string>meta.state.fdl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>;</string>
			<key>name</key>
			<string>punctuation.terminator.expression.fdl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>=&gt;</string>
			<key>name</key>
			<string>keyword.operator.state.fdl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\-\-|\+\+)</string>
			<key>name</key>
			<string>keyword.operator.increment-decrement.fdl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\-|\+|\*|/|%)</string>
			<key>name</key>
			<string>keyword.operator.arithmetic.fdl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)(!|&amp;&amp;|\|\|)</string>
			<key>name</key>
			<string>keyword.operator.logical.fdl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>&lt;&lt;|&gt;&gt;|~|\^|&amp;|\|</string>
			<key>name</key>
			<string>keyword.operator.bitwise.fdl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(==|&lt;=|&gt;=|&lt;&gt;|&lt;|&gt;)</string>
			<key>name</key>
			<string>keyword.operator.comparison.fdl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>=</string>
			<key>name</key>
			<string>keyword.operator.assignment.fdl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(if|then|else|use)\b</string>
			<key>name</key>
			<string>keyword.control.fdl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)(\$(bin|cycle|d(ec|isplay|p)|finish|hex|sfg|trace|option))\b</string>
			<key>name</key>
			<string>constant.language.fdl</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#types</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#numbers</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>numbers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)\b</string>
					<key>name</key>
					<string>constant.numeric.fdl</string>
				</dict>
			</array>
		</dict>
		<key>types</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(ns|tc|reg|sig)\b</string>
					<key>name</key>
					<string>storage.type.fdl</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.fdl</string>
	<key>uuid</key>
	<string>8C58C0C3-2D79-470A-B88E-BF0CFC70464A</string>
</dict>
</plist>
